<<<<<<< HEAD
project_id = "kpkntknwytegnmzdlzab"

[functions.public-checkout]
verify_jwt = false

[functions.financial-ai-chat]
verify_jwt = true

[functions.analytics-ai-chat]
verify_jwt = false
=======
project_id = "quofxsvpgpbsjqldrcyd"
>>>>>>> 6453443a20748151714003a9ab5b6ae418c70485
