project_id = "quofxsvpgpbsjqldrcyd"

[functions.public-checkout]
verify_jwt = false

[functions.financial-ai-chat]
verify_jwt = false

[functions.analytics-ai-chat]
verify_jwt = false

[functions.customer-ai-chat]
verify_jwt = false

[functions.asaas-subscription]
verify_jwt = false

[functions.asaas-account]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.facebook-conversions]
verify_jwt = false
