project_id = "quofxsvpgpbsjqldrcyd"

[functions.public-checkout]
verify_jwt = false

[functions.financial-ai-chat]
verify_jwt = true

[functions.analytics-ai-chat]
verify_jwt = false

[functions.customer-ai-chat]
verify_jwt = false

[functions.asaas-subscription]
verify_jwt = false
